.\" Copyright (c) 2011 Renzo Davoli
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License,
.\" version 2, as published by the Free Software Foundation.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston,
.\" MA 02110-1301 USA.

.TH VIEW-OS 1 "December 07, 2011" "VIEW-OS: a process with a view"
.SH NAME
um_console \- View-OS remote monitoring console client
.SH SYNOPSIS
.B um_console 
[
.I pid
]
.br
.B um_console -l
.br
.SH DESCRIPTION
\fBum_console\fR is the client to connect to a View-OS monitor console.

This feature is disabled by default. Use '-k' or '-K' option 
of \fBumview/kmview\fR to enable it.

The command \fBum_console -l\fR provides a list of available console
sessions.

\fIpid\fR can be omitted when \fBum_console\fR is used as a command of
a View-OS machine (in this case it gives access to the console of
the current View-OS monitor).

This command can be launched without parameters as a command of the 
hosting O.S. (outside any View-OS machine). In this case if there is
one single console available \fBum_console\fR gets connected to it,
otherwise the result is a list of the available session.

.SH SEE ALSO
.BR umview(1),
.BR kmview(1)
.SH AUTHORS
View-OS is a project of the Computer Science Department, University of
Bologna. Project Leader: Renzo Davoli.
.br
<http://www.sourceforge.net/projects/view-os>

Howto's and further information can be found on the project wiki
<wiki.virtualsquare.org>.
