.\" Copyright (c) 2006 Renzo Davoli
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License,
.\" version 2, as published by the Free Software Foundation.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston,
.\" MA 02110-1301 USA.

.TH VIEW-OS 1 "June 10, 2006" "VIEW-OS: a process with a view"
.SH NAME
um_lock_service \- lock service modules loaded by umview
.SH SYNOPSIS
.B um_lock_service 
[ 
.B -i 
]
.br
.SH DESCRIPTION
This command locks the modules loaded by umview.
After this command it is not possible to further add/delete/modify
the modules.
.SH OPTIONS
.IP "\fB\-i\fP" 4 
when lock is invoked with this option the service list becomes invisible,
i.e. it is not possible to have the list of loaded modules.
.SH SEE ALSO
.BR umview(1),
.BR um_add_service(1),
.BR um_del_service(1),
.BR um_ls_service(1),
.BR um_mov_service(1),
.BR umfuse(1viewos),
.BR lwipv6(1viewos),
.BR umdev(1viewos),
.BR umbinfmt(1viewos),
.BR viewfs(1viewos),
.SH AUTHORS
View-OS is a project of the Computer Science Department, University of
Bologna. Project Leader: Renzo Davoli. 
.br
<http://savannah.nongnu.org/projects/view-os>
