.\" Copyright (c) 2007 Renzo Davoli
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License,
.\" version 2, as published by the Free Software Foundation.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston,
.\" MA 02110-1301 USA.

.TH VIEW-OS 1 "June 11, 2007" "VIEW-OS: a process with a view"
.SH NAME
vuname \- print view information
.SH SYNOPSIS
.B vuname
[\fIOPTION\fR]...
.br
.SH DESCRIPTION
.PP
Print certain view information.  With no OPTION, same as \fB\-s\fR.
.SH OPTIONS
.IP "\fB\-a\fR, \fB\-\-all\fR" 4
print all information, in the following order, except omit \fB\-p\fR and \fB\-i\fR if unknown.
.IP "\fB\-s\fR, \fB\-\-kernel\-name\fR" 4
print the kernel name
.IP "\fB\-n\fR, \fB\-\-nodename\fR" 4
print the network node hostname
.IP "\fB\-r\fR, \fB\-\-kernel\-release\fR" 4
print the kernel release
.IP "\fB\-v\fR, \fB\-\-kernel\-version\fR" 4
print the kernel version
.IP "\fB\-m\fR, \fB\-\-machine\fR" 4
print the machine hardware name
.IP "\fB\-p\fR, \fB\-\-processor\fR" 4
print the processor type or "unknown"
.IP "\fB\-i\fR, \fB\-\-hardware\-platform\fR" 4
print the hardware platform or "unknown"
.IP "\fB\-o\fR, \fB\-\-operating\-system\fR" 4
print the operating system
.IP "\fB\-U\fR, \fB\-\-serverid\fR" 4
print the view-os server id
.IP "\fB\-V\fR, \fB\-\-viewid\fR" 4
print the view id
.IP "\fB\-N\fR, \fB\-\-viewname\fR" 4
print the view name
.IP "\fB\-x\fR, \fB\-\-nouname\fR" 4
do not use uname (without this flag the command behaves like uname 
		when it runs on a non View-OS enabled environment).
.IP "\fB\-q\fR, \fB\-\-quiet\fR" 4
quiet mode: error messages suppressed
.IP "\fB\-\-help\fR" 4
display a help message and exit
.IP "\fB\-\-version\fR" 4
output version information and exit

.SH SEE ALSO
.BR umview(1), uname(1)
.SH AUTHORS
View-OS is a project of the Computer Science Department, University of
Bologna. Project Leader: Renzo Davoli. 
.br
<http://www.sourceforge.net/projects/view-os>

Howto's and further information can be found on the project wiki
<wiki.virtualsquare.org>.

