.\" Copyright (c) 2009 Renzo Davoli
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License,
.\" version 2, as published by the Free Software Foundation.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston,
.\" MA 02110-1301 USA.

.TH VIEW-OS 1 "May 30, 2009" "VIEW-OS: a process with a view"
.SH NAME
um_fsalias \- define a file system type alias
.SH SYNOPSIS
.B um_fsalias 
.I fsalias
[
.I full_filesystem_type
]
.br
.SH DESCRIPTION
This command is used to define a short alias for a full qualified
view-os file system type.

For example
.br
\fBum_fsalias ext2 umfuseext2\fR
.br
defines ext2 as a short alias for umfuseext2. ext2 can then be used
in a \fBmount\fR command instead of the full name umfuseext2.

Further definitions of the same alias re-define the alias by overwriting
previous mappings.
If full_filesystem_type is omitted, the command deletes any previous
definition of the alias.

.SH SEE ALSO
.BR umview(1), 
.BR kmview(1)
.SH AUTHORS
View-OS is a project of the Computer Science Department, University of
Bologna. Project Leader: Renzo Davoli. 
.br
<http://www.sourceforge.net/projects/view-os>

Howto's and further information can be found on the project wiki
<wiki.virtualsquare.org>.

